"""empty message

Revision ID: 6b6a138fa5f9
Revises: a54291f20765
Create Date: 2019-03-13 20:07:00.291825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b6a138fa5f9'
down_revision = 'a54291f20765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_text', sa.Text(), nullable=False))
    op.alter_column('comment', 'blog_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('comment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment', mysql.TEXT(), nullable=False))
    op.alter_column('comment', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comment', 'blog_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('comment', 'comment_text')
    # ### end Alembic commands ###
